AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# See: https://github.com/aws-samples/serverless-patterns/blob/main/eventbridge-schedule-to-lambda/template.yaml
Description: >
  Simple stack that uses EventBridge schedules to trigger a lambda function.


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  ScheduledLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/demo/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64

  ScheduledLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [ ScheduledLambdaFunction ]
    Properties:
      LogGroupName: !Sub /aws/lambda/${ScheduledLambdaFunction}
      RetentionInDays: 7

  # 
  # ScheduleExpression: cron(0 0 * * ? *)
  # ScheduleExpressionTimezone: "America/New_York"
  #
  MyFirstSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: 'MySchedule'
      ScheduleExpression: 'rate(5 minute)'
      FlexibleTimeWindow:
        Mode: 'OFF'
      Target:
        Arn: !GetAtt ScheduledLambdaFunction.Arn
        RoleArn: !GetAtt MyFirstScheduleRole.Arn

  MyFirstScheduleRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: MyFirstScheduleRolePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt ScheduledLambdaFunction.Arn